package com.ecomerce.payment.service;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.ecomerce.payment.paymentGateway.PayemntGateway;
import com.razorpay.RazorpayException;
@Service
public class PaymentService {
    @Autowired
    PayemntGateway payemntGateway;

     public String initiatePayment(Long orderid, Long amount, String phoneNumber,String name) throws RazorpayException {
        // We need to make a call to the PG and return the
        // payment link generated by the PG

        return payemntGateway.generatePaymentLink(orderid, amount, phoneNumber,name);
    }
    
}
